### ISSUE TITLE
SQL Server integrated security ("driver is not configured for integrated authentication")

### ISSUE THREAD

**Issue by gfody** [ultorg/public_issues#14]
I'm getting this error trying to connect to a SQL Server instance with windows auth:

```
Connection failed: This driver is not configured for integrated authentication.
```

**Comment by eirikbakke** [comment]
Ah, I think I tried this once. There's a DLL file that must be downloaded to support this. I should figure out how to bundle it with Ultorg. You can try the following:

1) Got to https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc_auth/10.2.0.x64/dll and click "Downloads" in the upper right-hand corner, then click "dll". This will download the `mssql-jdbc_auth-10.2.0.x64.dll`, as distributed by Microsoft.
2) Put the downloaded DLL file in the ultorg\bin directory.
3) Then try adding the connection again, with ";integratedSecurity=true" added at the end of the JDBC URL.

Please do let me know if this works!

**Comment by gfody** [comment]
adding the dll did the trick thanks! I had to add `trustServerCertificate=true` as well as `integratedSecurity=true`

**Comment by eirikbakke** [comment]
Great to hear! There are so many authentication options available, it's useful to hear which specific errors people bump into.

**Comment by eirikbakke** [comment]
The TODO for this issue will be to bundle the DLL file and perhaps document the necessary parameters within the connection UI.

**Comment by eirikbakke** [comment]
Ultorg version 1.6.2 and later now bundles the DLL file that is needed for to connect to MSSQL with integrated authentication on Windows. I have updated the SQL Server related instructions on the [Download Ultorg](https://www.ultorg.com/download/) page, which will eventually be moved into a separate documentation page.

https://www.ultorg.com/releasenotes/#version-1_6_2
