### ISSUE TITLE
Data Editing: How to insert/delete rows?

### ISSUE THREAD

**Issue by eirikbakke** [ultorg/public_issues#20]
When working with tables in an external relational database, such as PostgreSQL, it is possible to use Ultorg to edit data from any perspective (visual query), using the Data Editing Mode button in the toolbar:

<img width="26" alt="DataEditingModeButton" src="https://user-images.githubusercontent.com/886243/167273888-c13a1387-2fbf-4acf-9b59-85663c2c2823.png">

With this mode enabled, you can edit primitive values in any database table by moving the cursor to the relevant cell and typing, like in a spreadsheet. Changes will appear in a "staged" state, and committed to the database in a single transaction only once you press the "Apply Edits" button:

<img width="777" alt="Staged Simple Edit" src="https://user-images.githubusercontent.com/886243/167274006-ddb35e80-a6c2-4199-a089-ea2035a72532.png">

You can also **insert** and **delete** rows, by using the key combinations Ctrl+Shift+Minus and Ctrl+Shift+Plus. (That's the plus/minus keys between 0 and Backspace, not on the numeric keypad.) The Ctrl+Shift+Minus action can also be used to revert any selected existing staged edits. Undo/Redo works here as well, until you press Apply Edits, after which committed changes cannot be undone.

TODO: Make the keyboard shortcuts work with +/- on the numeric keypad too.
TODO: Make these keyboard shortcuts documented in the user interface.

Pressing Ctrl+Shift+Minus will put the currently selected row in a pending delete state (red/strikeout):

<img width="772" alt="Staged Deletion" src="https://user-images.githubusercontent.com/886243/167274207-5035a5c4-cd44-4ad8-b33a-cd36827ec339.png">

Pressing Ctrl+Shift+Plus will show a "pending insert" row in green, where values for the new record can be entered:

<img width="925" alt="Staged Insert" src="https://user-images.githubusercontent.com/886243/167274459-cb3c0b96-0479-4ab6-ad6a-608778e65783.png">

When inserting new rows, it's usually best to make all of the table's available fields visible first, as done above, since you'd usually want to fill in values for them. In the example above, Ultorg has already populated the "Course ID" field, because the insert operation was done with the cursor located in one of the sections for the course with ID=3, in a perspective that has Sections joined on Courses on these two fields.

There are a few caveats for the row insertion feature (and fixing these are on the Ultorg TODO list):
* You will usually need to specify a primary key. In the screenshot above, Ultorg is showing a placeholder value "+1" that the user should change to a new primary key value. In the future, Ultorg will auto-generate primary keys at commit time, in columns for which this is enabled.
* In some perspectives, the inserted row may fail to show up in the expected place, in particular when the Custom Group feature has been used. In this case the status bar will show the message "Not all edits are currently visible", and it's usually best to invoke Undo to get out of this state. This problem will be fixed in a future Ultorg version.
* After staging some edits, it is still possible to make modifications to the perspective, e.g. to show additional fields. But if you apply filters, or make other changes to the query, the edits you had previously staged may no longer be visible (e.g. because they were in rows that are now filtered out). This will also cause the "Not all edits are currently visible" message to appear. It's best to keep the query in a state where all edits are visible before pressing Apply Edits, and future versions of Ultorg might enforce this.

**Comment by ldhieu** [comment]
Thanks for writing this out very clearly.

I just wanted to add that if anyone sees an error while adding rows saying type error "Expected Whole number, got Other", that's because you need to change the "+1", "+2", ... that ultorg places in ID rows to the corresponding IDs.

When editing multiple parent-child relationships, change the ID for the parent first, then add in the rows for the children otherwise the rows will get cleared out.

**Comment by eirikbakke** [comment]
@Idhieu Thanks for the comment! Both of those observations are exactly right. Each of these usability problems will need to be ironed out over future Ultorg versions.
