### ISSUE TITLE
Initial DB sync is opaque to the user

### ISSUE THREAD

**Issue by ejektaflex** [ultorg/public_issues#25]
I'm unable to see any tables after logging into an Oracle database. Note that my own schema has no tables - but I was hoping to see tables from all of the other schemas that exist in the DB. Is there something that I'm missing?
Thanks 🥲

**Comment by eirikbakke** [comment]
Hi! Yes, Ultorg is supposed to show all schemas that you have permission to see. Perhaps you could help me investigate with the following two steps?
1) First, make sure you have tried to expand the database icon in the "Folders" sidebar, by clicking the ">" to the left of the database cylinder icon.
2) Click Internals->Application Log and see if there are any error messages in the log.
3) Click Internals->Services, expand "Databases", and expand the rest of the icons to see if you see any tables there. (This is a separate debugging interface that uses a different method to retrieve the list of tables.)

**Comment by ejektaflex** [comment]
Actually, this has resolved itself for me. It turns out, it just took a minute or two to grab all of the information. There was no indicator that this was happening, so it seemed like nothing was working. A visual indicator that it is synchronizing would be excellent in the future!

**Comment by eirikbakke** [comment]
Great! You're right; there should be an indicator of some sort here. That will be the TODO for this issue (along with the related https://github.com/ultorg/public_issues/issues/8 ).

I do wonder why it took so long; perhaps you could still take a look at the log and see if you find anything odd, e.g. a huge number of requests. Or perhaps there was some throttling on the server side.

**Comment by ejektaflex** [comment]
The log did not specify anything odd at all - which was why I thought that nothing was working.

Both of those queries return ~10K rows in about 4s.

**Comment by eirikbakke** [comment]
@ejektaflex Thanks for testing! So are there actually 10,000 tables and views in the database? Are they showing up without any particular problems in the current version of Ultorg, once the initial load is done? I take it they are organized in various different schemas?

**Comment by ejektaflex** [comment]
Probably - I've never taken the time to count them ;) They're spread throughout a vast number of schemas.
The ones that I've checked look great, and they are organized correctly, yes!

**Comment by eirikbakke** [comment]
There's a proper "loading..." indication for schema reading operations implemented now, which will be in the next Ultorg release.

There's also a "no tables found" message for cases where the metadata operation completed but no tables were found (e.g. due to a misconfigured connection, like in https://github.com/ultorg/public_issues/issues/8 ).

![220722 Metadata Loading Indication](https://user-images.githubusercontent.com/886243/180574984-2e9a650b-7501-43c8-8d0a-93615880e996.png)

**Comment by eirikbakke** [comment]
Fixed in Ultorg 1.0.9, which is now released! The new Ultorg version is available at the old download link.

**Comment by LucaGabi** [comment]
@eirikbakke can I also join beta please?

**Comment by eirikbakke** [comment]
@LucaGabi Absolutely! Thanks for filling in the form on the website; I sent you an email link to download Ultorg!
