### ISSUE TITLE
Export/Import Perspectives and Data Source Configurations

### ISSUE THREAD

**Issue by eirikbakke** [ultorg/public_issues#32]
At the moment, perspectives and data source configurations are stored on the local machine only, and cannot be exported from one machine to another. This should be made possible.

Also pending are some related changes in the UI around creating and saving perspectives, tracked separately at https://github.com/ultorg/public_issues/issues/6 .

Since perspectives reference data sources, the user interface should help avoid exporting perspectives without their associated data source configuration. The system will also have to figure out how to deal with the case where the same data source already exists when importing.

Longer-term, there will be an "Ultorg Cloud" folder, next to the existing "Local Ultorg Folder", that can be used to share perspectives as well.

**Comment by DrRuhe** [comment]
This would allow better integration with other tools since other tools can act on a view (saved in a common machine-readable format). Currently, this requires opening the "Output" Tab and manually copying the SQL query or the JSON result.

For example, I use R to visualize data in a database, but use Ultorg to build the views. Then I load the data I want into R  using the SQL Query from Ultorg. If the views were saved as files  (let's assume json format for now), I could get the SQL Query from the file in R without having to copy/paste things around.

**Comment by eirikbakke** [comment]
I wonder what the best format would be for this kind of export.

Is it a goal here to be able to change the query in Ultorg and then have the R pipeline pick up on the changes to the query? Or is it a "static" query that is built once and then just needs to be able to run repeatedly from the R pipeline?

Also, when getting the data into R, is it supposed to be in a simple "flat"/tidy form, with rows and just primitive columns, like you get from a single SQL query? Or do you need nested one-to-many relationships of the kind that is seen in Ultorg's JSON output? (JSON arrays within other JSON arrays etc.)

**Comment by DrRuhe** [comment]
From my perspective it's probably best to allow separation of the view and the resulting data. For my example, it's not necessary to export the data as well. I'm using the query to get results without the limit from ultorg anyway. But in other situations I only need the data and do not  need the query. 

When exporting data, it would be nice to offer different options in regard to the output structure. For the R use case flat tables are preferred. But again, others use-cases might favor the nested structure.

In regards to changes being picked up, I'd say its suffcient to support saving the view, which updates the file. Then other tools can act on that.

**Comment by eirikbakke** [comment]
The latest Ultorg version (1.4.2) now allows folders of perspectives to be exported for import into another Ultorg installation (e.g. to share with other users, or for copying work to a different computer). I have created a separate issue https://github.com/ultorg/public_issues/issues/65 for the issue of letting external tools _other_ than Ultorg execute Ultorg-generated queries.

**Comment by DrRuhe** [comment]
Thanks :)
