### ISSUE TITLE
Validating / Controlling inputs

### ISSUE THREAD

**Issue by mkp-incom** [ultorg/public_issues#36]
Is it possible to implement functionality where any input (insert/update) is validated against some column in a table or specified as a list of valid inputs? I guess you kind of get this out of the box if foreign keys are defined on your schema, but I do think the option to set this lookup manually adds a lot of value.

**Comment by eirikbakke** [comment]
Are you thinking of a dropdown list of the kind that's mocked up in https://github.com/ultorg/public_issues/issues/19 ?

The plan for that feature was to have the dropdown list be triggered whenever the user is editing a single-column foreign key value. That way you get both the user interface benefit of the dropdown list and the data integrity benfit of a foreign key relationship that's enforced on the database side.

(Happy to chat to discuss... I'll reply to your email.)

**Comment by mkp-incom** [comment]
Ah sorry, I did miss that one (did try to skim the already submitted tickets), that is exactly what I was thinking off - just a small comment, I think this feature should not be dependent on actual foreign keys - its ok to auto populate the list/validation based on that, but I'd really like that you could also:
1. Define the list by pointing to another column in table x (could be the same table as the column already resides in, could be another table)
2. Define you own list of values

**Comment by eirikbakke** [comment]
This feature is now implemented in Ultorg 1.2.2 and with various adjustments in Ultorg 1.2.3 and 1.2.4. See https://github.com/ultorg/public_issues/issues/19 or https://www.ultorg.com/releasenotes/ for screenshots.

Existing Ultorg users can find the latest version at the old download link. Thanks for this feature request!
