### ISSUE TITLE
Adding default logging parameters/values when inserting/updating records

### ISSUE THREAD

**Issue by mkp-incom** [ultorg/public_issues#37]
Is it possible to add default variables to columns (like "username" or "currenttimestamp"), and also perhaps set these to be used i.e mapped to specific columns in the tables(s) you are editing. I know that some of that functionality can be solved by the respective database-engine utilizing default values or triggers etc. But being able to set them within UltOrg does provide a nice feature (at least for my usecase).

**Comment by eirikbakke** [comment]
I'll have to think a bit about where to save these kinds of settings. Ideally, as you say, they belong with the database schema, in the backend.

One planned feature is to have Ultorg let you edit the actual database schema; create tables, add/remove columns, set data types, etc. In this context it would be natural to let the user specify default values for columns. Would this help your use case, or are you specifically looking for a solution that does not modify the database schema?

**Comment by mkp-incom** [comment]
Specifically I'm thinking about a solution that stays within the application and only writes data to specific columns. The use case would be to have CreatedBy/ModifiedBy / CreatedOn/ModifiedBy columns defined in the tables that UltOrg is maintaining and then setting these every time data is inserted or changed. The datetimes would then just be some internal variable (consider handling timezones) and the user would be derived from the user using the application (not the user defined in the connectionstring for the source).

**Comment by eirikbakke** [comment]
This feature was added in Ultorg version 1.2.3; see https://www.ultorg.com/releasenotes/ for details. Existing Ultorg users can find the latest version at the old download link. Thanks for this feature request!

![editbehaviors](https://user-images.githubusercontent.com/886243/198340116-80221970-7bf1-4777-ae84-f341f50039a7.png)
