### ISSUE TITLE
Cannot do Aggregates in 1.2.0

### ISSUE THREAD

**Issue by ejektaflex** [ultorg/public_issues#39]
Attempting an aggregate results in an error. here is the result of my adding a new column to a group for a simple sum:

![image](https://user-images.githubusercontent.com/23628421/189519181-ee66808d-7ca4-40cd-8806-020ab29cd424.png)

**Comment by eirikbakke** [comment]
Which database type is this? MySQL, MariaDB, PostgresSQL, Microsoft SQL Server, Oracle, or SQLite?

**Comment by eirikbakke** [comment]
Also, what is the data type of the column you are trying to SUM?

**Comment by eirikbakke** [comment]
You can find the database's data type for each column by clicking the small icon in the top right-hand corner of the "Fields" sidebar, then selecting "Backend Type Name" and clicking OK. See the screenshot below.

<img width="772" alt="Backend type" src="https://user-images.githubusercontent.com/886243/189533032-8c6dad56-1f1f-42dd-9909-0dc88669fd07.png">

I remember you were using Oracle before, but I tried and didn't get the error when doing a SUM on a regular NUMBER column.

**Comment by ejektaflex** [comment]
Oh, this is using an SQLite file. I know it's a bit untested (or, at least, it used to be) and I forgot about that.

I have several records grouped together by a person's name, and I'm adding a new SUM(price) for each person to get a total price of items purchased by each person. As such, the person's name has no backend value but it would be a TEXT. The prices are each a NUMERIC.

**Comment by eirikbakke** [comment]
Ah, great, now I managed to reproduce it, and fix it. I'll let you know when a new release is out.

Eventually I'll do more work on the SQLite dialect, and get the integration test suite passing on it. Once that is done, there should be fewer surprises.

**Comment by eirikbakke** [comment]
There's a new Ultorg release up now, at the old download link, which fixes this bug.

Thanks for reporting!
