### ISSUE TITLE
Don't break old Versions

### ISSUE THREAD

**Issue by jg-cantaa** [ultorg/public_issues#45]
I just wanted to use Ultorg again, after it has been some time. While I appreciate the notice about new versions being available, I did not like the fact that it closes the application.

I know that you want feedback for the latest version, however users might not want to update every time.

I'd like there to be a "I know that newer Versions might include certain fixes and features, but keep using anyway" button.

**Comment by eirikbakke** [comment]
Sorry about that! This will change in the future, once Ultorg is out of beta. Agreed that the user should be able to choose whether to upgrade or not.

Meanwhile you can find the latest version at the same download link you used before (or fill in https://www.ultorg.com/signup/ again to receive a new link).

**Comment by eirikbakke** [comment]
Ultorg is now out of beta! In the new versions, users will no longer be always forced to upgrade to the latest version.

As you suggested, there is still a message that will tell users if there are new updates available, but they are now optional. The exception might be if there are mandatory security updates or such (which should be rare).
