### ISSUE TITLE
Snowflake support

### ISSUE THREAD

**Issue by roolio** [ultorg/public_issues#46]
Hello, and kudos for Ultorg, I really like the product! No equivalent there. 

I was wondering if Snowflake support was planned? Or maybe if there were some generic (jdbc) ways to connect a database to Ultorg

Thxs

**Comment by eirikbakke** [comment]
Thanks for the suggestion! I've had a few other users request Snowflake connections before.

I created a test account today and added some initial support for their SQL dialect. It'll be in the next Ultorg release, as an experimental feature!

**Comment by roolio** [comment]
great news! thanks a lot!

**Comment by eirikbakke** [comment]
There's a new Ultorg version (1.2.6) that adds experimental support for Snowflake connections now. You can find it at your old download link, or send me an email at ebakke@ultorg.com!

**Comment by roolio** [comment]
Got it, tested it, it works for me! Thanks a lot again

**Comment by eirikbakke** [comment]
Excellent; thanks for testing! How do you find the performance while browsing Snowflake tables with Ultorg? (I haven't done any Snowflake-specific optimizations at this point...)

**Comment by roolio** [comment]
Hello, hard to describe quantitatively, but qualitatively I'd say it's rather positive : the tables were large (in width and length), and the UX while exploring the data was not a deal breaker at all. Sorry again for the fluffyness of the feedback :)

**Comment by eirikbakke** [comment]
@roolio Great, that's useful to know. Thanks!
