### ISSUE TITLE
Can't find the "disable prettification option"

### ISSUE THREAD

**Issue by wizzard0** [ultorg/public_issues#56]
I've seen in #49 that it should be possible to disable prettification, but can't find it anywhere. Just explored every menu item and every settings item, no luck :/

My table names contain a lot of mixed-case abbreviations (e.g. `metrics_mDNS` and `rateUAHxUSDdelta` which gets turned into `Rate Uahx Usddelta` 🤯 ) and at times it's really hard to guess what was the original name at times ((

**Comment by eirikbakke** [comment]
There's a button in the toolbar, shown in the screenshot below. Did you find it, and did it not have any effect? What kind of data source is this?

(I also have on my TODO list to populate the main menu bar with all the actions that are currently found only in toolbars and context menus.)
 
![prettybutton](https://github.com/ultorg/public_issues/assets/886243/75138c45-fcbe-42ec-a7a2-e5851bc6d57d)

**Comment by eirikbakke** [comment]
There's a new Ultorg release now, which adds an option to disable table/column name prettification at the data source level:

![auto_format_field_names](https://github.com/ultorg/public_issues/assets/886243/eb41ac8f-af2e-43ad-b526-d87cb2813742)

The option to override the setting at the individual perspective level is still available, but has been de-emphasized and moved from the toolbar to the Format menu (under the new name "Auto-Format Table/Column Names").

The options should now also be more discoverable, as there is now an entry in the main menu bar for the settings (under Data: Other Data Source Options).

The latest Ultorg version is available at https://www.ultorg.com/download/ , with all trial periods having been reset for this release. See the [Release Notes](https://www.ultorg.com/releasenotes/) for a full list of improvements.
