### ISSUE TITLE
1.2.8 "can't verify license"

### ISSUE THREAD

**Issue by wizzard0** [ultorg/public_issues#57]
Just updated to 1.2.8 and it's great but I restarted it so it would detect new tables (how to do it without restart btw?) and stopped working - just displays "Could not verify license" and then exits ((

<img width="677" alt="image" src="https://github.com/ultorg/public_issues/assets/424619/0ebfcd95-605e-41c0-9e97-07aefcbbc70b">

**Comment by eirikbakke** [comment]
I think it's an internet connection issue, especially if it worked before. Hopefully it should work if you try again?

This dialog will soon go away and be replaced with a more traditional activation flow, which will also work offline (like IntelliJ does it).

**Comment by msimanga** [comment]
Just bumping this up. I am on 1.3.0 and getting same error. I think company firewall is blocking the internet connection from Ultorg.

**Comment by eirikbakke** [comment]
Thanks for the report! Yes, this happens when the beta version of Ultorg is unable to access the Internet on startup (which is often the case in corporate environments that block all apps other than Chrome from the Internet). I'm working on the billing & license management system for the public release of Ultorg, which will include an offline activation option.

**Comment by eirikbakke** [comment]
Ultorg is now out of beta! The new versions have a new activation mechanism which should make the app work completely offline after initial activation. The initial activation can also be done offline via an activation code.

I've also changed a few things to try to make the online activation mechanism work better with corporate proxy servers.

![activationWizard](https://github.com/ultorg/public_issues/assets/886243/a3660d1a-600e-4e43-abb7-74e074deb4c0)

Initially, Ultorg will be a paid app with a free trial period, available at https://www.ultorg.com/

>  so it would detect new tables (how to do it without restart btw?)

Oh, and i missed this question before. When Ultorg is open, you can right-click the data source icon in the Folders pane and click "Refresh Table Metadata".
